table dTituloNCR
	lineageTag: cb63ec5f-ffc8-4583-a8a8-dbb46f3fe7be

	column E1_NUM
		dataType: string
		lineageTag: 848e8688-f7f2-42ec-b3d9-1ff486ea96e1
		summarizeBy: none
		sourceColumn: E1_NUM

		annotation SummarizationSetBy = Automatic

	column E1_VALOR
		dataType: double
		lineageTag: ffdf0011-2d60-4a63-b109-d552316d1064
		summarizeBy: sum
		sourceColumn: E1_VALOR

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column E1_SALDO
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 3110551e-9270-4856-919a-be35ef132d78
		summarizeBy: sum
		sourceColumn: E1_SALDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	column STATUS_LIQUID
		dataType: string
		lineageTag: faca4057-3d9a-4264-ada4-62a5eb6cbf62
		summarizeBy: none
		sourceColumn: STATUS_LIQUID

		annotation SummarizationSetBy = Automatic

	column E1_FILIAL
		dataType: string
		lineageTag: 59d7188f-72c1-411b-ba9a-9ea169fa99a6
		summarizeBy: none
		sourceColumn: E1_FILIAL

		annotation SummarizationSetBy = Automatic

	column PK_TITULONCR
		dataType: string
		lineageTag: ab81ea67-5fe6-4e8b-9803-960fcd6316ec
		summarizeBy: none
		sourceColumn: PK_TITULONCR

		annotation SummarizationSetBy = Automatic

	column FK_CLIENTE
		dataType: string
		lineageTag: bee9562d-e66c-4c08-bfe4-205447b9a2fd
		summarizeBy: none
		sourceColumn: FK_CLIENTE

		annotation SummarizationSetBy = Automatic

	column E1_EMISSAO
		dataType: dateTime
		formatString: Short Date
		lineageTag: 310c8ba1-b4a7-49d7-b3b4-1bca330ce76c
		summarizeBy: none
		sourceColumn: E1_EMISSAO

		variation Variation
			isDefault
			relationship: a1817950-f7a1-4a2e-8045-b68021ee1680
			defaultHierarchy: LocalDateTable_29388b52-c3e2-444d-8e42-78dc69527b63.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column VENDEDOR
		dataType: string
		lineageTag: 70e76e8f-e600-48ca-b05b-dde40506a0ea
		summarizeBy: none
		sourceColumn: VENDEDOR

		annotation SummarizationSetBy = Automatic

	column COD_CLIENTE
		dataType: string
		lineageTag: 8ee59e64-03e3-4a71-ba59-25a121fcf719
		summarizeBy: none
		sourceColumn: COD_CLIENTE

		annotation SummarizationSetBy = Automatic

	column NOME_CLIENTE
		dataType: string
		lineageTag: 4bf7c267-3969-4405-9312-b30ec1c8932b
		summarizeBy: none
		sourceColumn: NOME_CLIENTE

		annotation SummarizationSetBy = Automatic

	partition dTituloNCR = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("192.168.0.244", "DADOSP12", [Query="DECLARE @DATE datetime = DATEADD(YEAR, -1, GETDATE())#(lf)#(lf);WITH CTE AS (SELECT E1_NUM, E1_BAIXA, E1_VEND1, E1_LOJA, A3_CLIENTE, A3_LOJACLI, E1_CLIENTE, E1_NOME#(lf)FROM SE1010 SE1#(lf)LEFT JOIN SA3010 SA3 ON A3_COD = E1_VEND1 AND SA3.D_E_L_E_T_ = '' AND A3_FILIAL = '01'#(lf)WHERE SE1.D_E_L_E_T_ = '' AND E1_TIPO = 'NF') ----PREPARA OS TÍTULOS ORIGINAIS DE CADA NCR, VISANDO O INNER JOIN COM SE1 DE NCR#(lf)#(lf)SELECT#(lf)E1_FILIAL, #(lf)SE1.E1_CLIENTE VENDEDOR,#(lf)E1_EMISSAO,#(lf)SE1.E1_NUM,#(lf)CTE.E1_CLIENTE COD_CLIENTE,#(lf)A1_NOME NOME_CLIENTE,#(lf)SUM(E1_VALOR) E1_VALOR,#(lf)SUM(E1_SALDO) E1_SALDO,#(lf)CASE WHEN SUM(E1_SALDO) > 0 THEN 'A LIQUIDAR' ELSE 'LIQUIDADO' END AS STATUS_LIQUID,#(lf)TRIM(E1_FILIAL) + '|' + TRIM(SE1.E1_NUM) AS PK_TITULONCR,#(lf)TRIM(SE1.E1_CLIENTE) + '|' + TRIM(SE1.E1_LOJA) AS FK_CLIENTE#(lf)FROM SE1010 SE1#(lf)INNER JOIN CTE ON CTE.E1_NUM = SE1.E1_NUM AND CTE.A3_CLIENTE = SE1.E1_CLIENTE  -- FAZ O INNER JOIN COM O CÓDIGO DE CLIENTE DE CADA VENDEDOR DA NOTA FISCAL COM O CLIENTE GERADO NO NCR, TRAZENDO ASSIM A NOTA FISCAL CORRENTE, POSSIBILITADNO TRAZER O CLIENTE QUE GEROU O NCR#(lf)INNER JOIN SA1010 SA1 ON A1_COD = CTE.E1_CLIENTE AND A1_LOJA = CTE.E1_LOJA AND SA1.D_E_L_E_T_ = '' AND A1_FILIAL = '01'#(lf)WHERE SE1.D_E_L_E_T_ = '' AND E1_EMISSAO >= @DATE AND E1_PREFIXO = 'NCR'#(lf)GROUP BY SE1.E1_NUM, E1_FILIAL, SE1.E1_CLIENTE, SE1.E1_LOJA, E1_PREFIXO, E1_EMISSAO, CTE.E1_CLIENTE, A1_NOME#(lf)#(lf)#(lf)"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"E1_EMISSAO", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

