table dTituloNCC
	lineageTag: 0f6310c6-b914-40b6-9e19-7bdcbfbcd562

	column E1_FILIAL
		dataType: string
		lineageTag: 555ebf09-3481-4a03-ad1d-e1eb5f6d6071
		summarizeBy: none
		sourceColumn: E1_FILIAL

		annotation SummarizationSetBy = Automatic

	column E1_NUM
		dataType: string
		lineageTag: 05dec10e-9002-4115-bce7-024d38c1ad7e
		summarizeBy: none
		sourceColumn: E1_NUM

		annotation SummarizationSetBy = Automatic

	column E1_SALDO
		dataType: double
		lineageTag: 0e71aadc-9293-4424-af54-b98c89e22a64
		summarizeBy: sum
		sourceColumn: E1_SALDO

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column EMISSAO
		dataType: dateTime
		formatString: Long Date
		lineageTag: c1cbe083-e9b9-4c45-91a9-ea27f44ed1c3
		summarizeBy: none
		sourceColumn: EMISSAO

		variation Variation
			isDefault
			relationship: afe62fba-783d-4cd8-9d0f-51c83b7bdb9b
			defaultHierarchy: LocalDateTable_ecf29102-d54e-4392-8b67-1175c24465d4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PK_TITULO
		dataType: string
		lineageTag: a5b97f88-1934-4aa0-af9d-aedbb76b053f
		summarizeBy: none
		sourceColumn: PK_TITULO

		annotation SummarizationSetBy = Automatic

	column A1_COD
		dataType: string
		lineageTag: 4eb06f2d-0694-4cb7-883c-b5cf8f25098b
		summarizeBy: none
		sourceColumn: A1_COD

		annotation SummarizationSetBy = Automatic

	column A1_NOME
		dataType: string
		lineageTag: e0996627-edba-48d9-a47a-791923118e06
		summarizeBy: none
		sourceColumn: A1_NOME

		annotation SummarizationSetBy = Automatic

	partition dTituloNCC = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("192.168.0.244", "DADOSP12", [Query="DECLARE @DATE datetime = DATEADD(YEAR, -1, GETDATE())#(lf)#(lf)SELECT DISTINCT#(lf)E1_FILIAL, #(lf)E1_NUM,#(lf)A1_COD, #(lf)A1_NOME,#(lf)SUM(E1_SALDO) OVER (PARTITION BY E1_FILIAL, E1_NUM) E1_SALDO,#(lf)MIN(E1_EMISSAO) OVER (PARTITION BY E1_FILIAL, E1_NUM) AS EMISSAO,#(lf)TRIM(E1_FILIAL) + '|' + TRIM(E1_NUM) + '|' + TRIM(E1_PREFIXO) + '|' + TRIM(E1_CLIENTE) + '|' + TRIM(E1_LOJA) AS PK_TITULO#(lf)FROM SE1010 SE1#(lf)INNER JOIN SA3010 SA3 ON E1_VEND1 = A3_COD AND A3_FILIAL = '01' AND SA3.D_E_L_E_T_ = ''#(lf)INNER JOIN SA1010 SA1 ON A1_COD = A3_CLIENTE AND A1_LOJA = A3_LOJACLI AND A1_FILIAL = '01'#(lf)WHERE SE1.D_E_L_E_T_ = '' AND E1_EMISSAO >= @DATE AND LEFT(E1_FILIAL,2) = '01'"]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"EMISSAO", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

