table Tabela1
	lineageTag: b3c091f2-5aae-4d21-91e7-2482547d3be7

	column PK_TABELA1
		dataType: string
		lineageTag: bc36ab96-b3ae-4b48-b5b0-57351a0eaab6
		summarizeBy: none
		sourceColumn: PK_TABELA1

		annotation SummarizationSetBy = Automatic

	column CODIGO_TABELA
		dataType: string
		lineageTag: cd67153c-3750-4484-ba1d-1d2ea39d1f99
		summarizeBy: none
		sourceColumn: CODIGO_TABELA

		annotation SummarizationSetBy = Automatic

	column CODIGO_PRODUTO
		dataType: string
		lineageTag: 0cfd1150-a984-4e2f-8f96-8d85be999dac
		summarizeBy: none
		sourceColumn: CODIGO_PRODUTO

		annotation SummarizationSetBy = Automatic

	column DATA
		dataType: dateTime
		formatString: Short Date
		lineageTag: 859a4ac6-1454-46b0-9060-6cf9a14a4086
		summarizeBy: none
		sourceColumn: DATA

		variation Variation
			isDefault
			relationship: b9d32f80-ad19-4817-81d5-9664d89f433d
			defaultHierarchy: LocalDateTable_b242e3f3-dd52-4db2-9ac3-3bae24274188.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column PRECO_TABELA
		dataType: double
		formatString: "R$"\ #,0.00;-"R$"\ #,0.00;"R$"\ #,0.00
		lineageTag: 27f85504-f64f-4e06-889b-4459370b92c8
		summarizeBy: sum
		sourceColumn: PRECO_TABELA

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"currencyCulture":"pt-BR"}

	partition Tabela1 = m
		mode: import
		source =
				let
				    Fonte = Sql.Database("192.168.0.244", "Data Warehouse", [Query="SELECT CODIGO_PRODUTO + '|' + PrecoTabela.DATA as PK_TABELA1,#(lf)CODIGO_TABELA,#(lf)RIGHT(CODIGO_PRODUTO,5) CODIGO_PRODUTO,#(lf)DATA,#(lf)PRECO_TABELA#(lf)FROM PrecoTabela#(lf)WHERE CODIGO_TABELA = '003'"]),
				    #"Tipo Alterado1" = Table.TransformColumnTypes(Fonte,{{"DATA", type date}}),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Tipo Alterado1",{{"DATA", type date}}),
				    #"Duplicatas Removidas" = Table.Distinct(#"Tipo Alterado", {"PK_TABELA1"})
				in
				    #"Duplicatas Removidas"

	annotation PBI_ResultType = Table

	annotation PBI_NavigationStepName = Navegação

