table dCalendario
	lineageTag: a2aeeee3-5d8d-42f8-addc-a19cfd1ae2bb

	column Data
		dataType: dateTime
		formatString: Short Date
		lineageTag: 2b951d25-6433-49f5-8145-817b33b8d627
		summarizeBy: none
		sourceColumn: Data

		variation Variation
			isDefault
			relationship: 91eae191-ef92-4b56-9a96-1ec2b98c260d
			defaultHierarchy: LocalDateTable_06c92ffe-c234-4f3a-a566-26549d11cec4.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column Ano
		dataType: int64
		formatString: 0
		lineageTag: e95cf47b-6a59-411a-9007-164105092566
		summarizeBy: sum
		sourceColumn: Ano

		annotation SummarizationSetBy = Automatic

	column Mês
		dataType: int64
		formatString: 0
		lineageTag: 198d12a5-c5fd-4a2f-864b-d26cf36eed71
		summarizeBy: sum
		sourceColumn: Mês

		annotation SummarizationSetBy = Automatic

	column 'Nome Mês'
		dataType: string
		lineageTag: d25c4399-a85e-4d99-a0bf-c59e63b9b08f
		summarizeBy: none
		sourceColumn: Nome Mês

		annotation SummarizationSetBy = Automatic

	column Dia
		dataType: int64
		formatString: 0
		lineageTag: 1cd939a7-2fa4-4e49-95b3-da4793ef8625
		summarizeBy: sum
		sourceColumn: Dia

		annotation SummarizationSetBy = Automatic

	column 'Dia da Semana'
		dataType: int64
		formatString: 0
		lineageTag: e7262b63-92ae-4a1d-bcbb-c712094d2842
		summarizeBy: sum
		sourceColumn: Dia da Semana

		annotation SummarizationSetBy = Automatic

	column 'Nome do Dia'
		dataType: string
		lineageTag: 6c3bbe19-461f-407c-9a1b-54cd68a1168b
		summarizeBy: none
		sourceColumn: Nome do Dia

		annotation SummarizationSetBy = Automatic

	column Trimestre
		dataType: string
		lineageTag: 8de2cbdb-8054-45f6-9183-1bfca5e36586
		summarizeBy: none
		sourceColumn: Trimestre

		annotation SummarizationSetBy = Automatic

	column Ano-Mês
		dataType: string
		lineageTag: dcb96488-45f6-42fe-a3bf-3cf1362e77bd
		summarizeBy: none
		sourceColumn: Ano-Mês

		annotation SummarizationSetBy = Automatic

	partition dCalendario = m
		mode: import
		source = ```
				let
				    // Definir a data inicial e final
				    DataInicial = #date(2000, 1, 1),  // Altere conforme necessário
				    DataFinal = #date(2050, 1, 1),  // Data de hoje
				
				    // Criar uma lista de datas entre a data inicial e final
				    ListaDatas = List.Dates(DataInicial, Number.From(DataFinal - DataInicial) + 1, #duration(1, 0, 0, 0)),
				
				    // Transformar a lista em uma tabela
				    TabelaDatas = Table.FromList(ListaDatas, Splitter.SplitByNothing(), {"Data"}),
				
				    // Adicionar colunas auxiliares
				    TipoAlterado = Table.TransformColumnTypes(TabelaDatas, {{"Data", type date}}),
				    AdicionarAno = Table.AddColumn(TipoAlterado, "Ano", each Date.Year([Data]), Int64.Type),
				    AdicionarMes = Table.AddColumn(AdicionarAno, "Mês", each Date.Month([Data]), Int64.Type),
				    AdicionarNomeMes = Table.AddColumn(AdicionarMes, "Nome Mês", each Date.ToText([Data], "MMMM"), type text),
				    AdicionarDia = Table.AddColumn(AdicionarNomeMes, "Dia", each Date.Day([Data]), Int64.Type),
				    AdicionarDiaSemana = Table.AddColumn(AdicionarDia, "Dia da Semana", each Date.DayOfWeek([Data]) + 1, Int64.Type),
				    AdicionarNomeDia = Table.AddColumn(AdicionarDiaSemana, "Nome do Dia", each Date.ToText([Data], "dddd"), type text),
				    AdicionarTrimestre = Table.AddColumn(AdicionarNomeDia, "Trimestre", each "Q" & Number.ToText(Date.QuarterOfYear([Data])), type text),
				    AdicionarAnoMes = Table.AddColumn(AdicionarTrimestre, "Ano-Mês", each Text.PadStart(Text.From([Ano]), 4, "0") & "-" & Text.PadStart(Text.From([Mês]), 2, "0"), type text)
				    
				in
				    AdicionarAnoMes
				```

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

