table Investimentos
	lineageTag: fb1df387-7126-44c4-96c0-bf58b7d3ea1f

	column 'Nome da campanha'
		dataType: string
		lineageTag: 7b067a6b-bc6b-4183-a22b-e19c7325486d
		summarizeBy: none
		sourceColumn: Nome da campanha

		annotation SummarizationSetBy = Automatic

	column 'Tipo de resultado'
		dataType: string
		lineageTag: c5b5fadb-1127-4461-960e-9e0dd910bf70
		summarizeBy: none
		sourceColumn: Tipo de resultado

		annotation SummarizationSetBy = Automatic

	column Resultados
		dataType: int64
		formatString: 0
		lineageTag: 1913be8e-bbbb-4035-a37c-99b38d87e31d
		summarizeBy: sum
		sourceColumn: Resultados

		annotation SummarizationSetBy = Automatic

	column 'Valor usado (BRL)'
		dataType: double
		lineageTag: c051280a-3021-4437-a192-e8e703d03a07
		summarizeBy: sum
		sourceColumn: Valor usado (BRL)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column 'Conversas por mensagem iniciadas'
		dataType: int64
		formatString: 0
		lineageTag: cfe221af-ca70-4172-b039-3ff513872109
		summarizeBy: sum
		sourceColumn: Conversas por mensagem iniciadas

		annotation SummarizationSetBy = Automatic

	column 'Custo por resultado'
		dataType: double
		lineageTag: 3a30a0b8-3902-4a3e-a25a-85ef866b64bd
		summarizeBy: sum
		sourceColumn: Custo por resultado

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Alcance
		dataType: int64
		formatString: 0
		lineageTag: 36b82de1-3781-4e7f-8fea-3834366e43b5
		summarizeBy: sum
		sourceColumn: Alcance

		annotation SummarizationSetBy = Automatic

	column 'Status de veiculação'
		dataType: string
		lineageTag: 775664ee-3479-4f0e-b68e-ba33709d0b9c
		summarizeBy: none
		sourceColumn: Status de veiculação

		annotation SummarizationSetBy = Automatic

	column 'Nível de veiculação'
		dataType: string
		lineageTag: 76c87e87-850b-4790-8425-8c9c98821936
		summarizeBy: none
		sourceColumn: Nível de veiculação

		annotation SummarizationSetBy = Automatic

	column 'CPM (custo por 1.000 impressões)'
		dataType: double
		lineageTag: f0758298-ea18-41aa-84c1-905f01de7278
		summarizeBy: sum
		sourceColumn: CPM (custo por 1.000 impressões)

		annotation SummarizationSetBy = Automatic

		annotation PBI_FormatHint = {"isGeneralNumber":true}

	column Objetivo
		dataType: string
		lineageTag: eaa31e93-bd68-4cb4-ae7c-c13f3493d892
		summarizeBy: none
		sourceColumn: Objetivo

		annotation SummarizationSetBy = Automatic

	column Impressões
		dataType: int64
		formatString: 0
		lineageTag: be5646e1-9076-489a-97c9-c634535d4b68
		summarizeBy: sum
		sourceColumn: Impressões

		annotation SummarizationSetBy = Automatic

	column 'Início dos relatórios'
		dataType: dateTime
		formatString: Long Date
		lineageTag: d76fd7d7-4094-4b1b-b99d-3ac5bd8d8407
		summarizeBy: none
		sourceColumn: Início dos relatórios

		variation Variation
			isDefault
			relationship: 7ec09c8d-6c55-4bcb-ac8b-15a4fa58e987
			defaultHierarchy: LocalDateTable_e09104ee-a796-4011-850c-c09907b81805.'Hierarquia de datas'

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	column 'Término dos relatórios'
		dataType: dateTime
		formatString: Short Date
		lineageTag: 5c242c0f-1a27-4f7f-b305-cb14a198481d
		summarizeBy: none
		sourceColumn: Término dos relatórios

		annotation SummarizationSetBy = Automatic

		annotation UnderlyingDateTimeDataType = Date

	partition Investimentos = m
		mode: import
		source =
				let
				    Fonte = Excel.Workbook(File.Contents("\\TROP-FS1\tropintranet$\Setores\Comunicacao\16 - B.I Tráfego pago\Planilhas\Relatório Meta ADS - Formatado.xlsx")),
				    #"Formatted Report_sheet" = Fonte{[Item="Formatted Report",Kind="Sheet"]}[Data],
				    FilterNullAndWhitespace = each List.Select(_, each _ <> null and (not (_ is text) or Text.Trim(_) <> "")),
				    #"Linhas Superiores Removidas" = Table.Skip(#"Formatted Report_sheet", each try List.IsEmpty(List.Skip(FilterNullAndWhitespace(Record.FieldValues(_)), 2)) otherwise false),
				    #"Outras Colunas Removidas" = Table.SelectColumns(#"Linhas Superiores Removidas", List.Select(Table.ColumnNames(#"Linhas Superiores Removidas"), each try not List.IsEmpty(FilterNullAndWhitespace(Table.Column(#"Linhas Superiores Removidas", _))) otherwise true)),
				    #"Cabeçalhos Promovidos" = Table.PromoteHeaders(#"Outras Colunas Removidas", [PromoteAllScalars=true]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(#"Cabeçalhos Promovidos",{{"Nome da campanha", type text}, {"Tipo de resultado", type text}, {"Resultados", Int64.Type}, {"Valor usado (BRL)", type number}, {"Conversas por mensagem iniciadas", Int64.Type}, {"Custo por resultado", type number}, {"Alcance", Int64.Type}, {"Status de veiculação", type text}, {"Nível de veiculação", type text}, {"CPM (custo por 1.000 impressões)", type number}, {"Objetivo", type text}, {"Impressões", Int64.Type}, {"Início dos relatórios", type date}, {"Término dos relatórios", type date}})
				in
				    #"Tipo Alterado"

	annotation PBI_NavigationStepName = Navegação

	annotation PBI_ResultType = Table

