table 'Medidas - Temporais'
	lineageTag: d5f23015-399e-490b-af24-0b934da1b510

	measure '# Inativos Mês Passado' = ```
			
			CALCULATE(
			    [# Total Clientes/Métricas],
			    FILTER(
			        dCliente,
			        MONTH(dCliente[MES_INATIVO]) +1 IN VALUES(dCalendario[Mês])  &&
			        YEAR(dCliente[MES_INATIVO]) IN VALUES(dCalendario[Ano])
			    ),
			    dCliente[STATUS] = "INATIVO"
			)
			
			```
		formatString: 0
		lineageTag: 24b8eb30-dfaa-4e45-a5a0-f242aad16422

	measure '# Clientes Positivados Mês -1' = ```
			
			CALCULATE(
			    [# Total Clientes/Métricas],
			    FILTER(
			        dCliente,
			        MONTH(dCliente[PRIMEIRA_COMPRA]) +1 IN VALUES(dCalendario[Mês]) &&
			        YEAR(dCliente[PRIMEIRA_COMPRA]) IN VALUES(dCalendario[Ano])
			    )
			)
			
			```
		formatString: 0
		lineageTag: acf8e9ad-aabe-498a-ae94-d0d43a19ad20

	measure '# Clientes repositivados Mês -1' = CALCULATE(COUNT(fctFaturamento[PK_CLIENTE]), fctFaturamento[COMPRAS_DIFERENCA_DIA] >= 90, dCliente[SEGMENTACAO_ATIVIDADE_8] = "000907", PREVIOUSMONTH(dCalendario[Data]))
		formatString: 0
		lineageTag: 95fd1eb8-b714-4a12-aa25-628329346beb

	column 'Coluna 1'
		dataType: string
		lineageTag: 148eec78-a632-4a19-b7c1-ded5da7aad3b
		summarizeBy: none
		sourceColumn: Coluna 1

		annotation SummarizationSetBy = Automatic

	partition 'Medidas - Temporais' = m
		mode: import
		source =
				let
				    Fonte = Table.FromRows(Json.Document(Binary.Decompress(Binary.FromText("i44FAA==", BinaryEncoding.Base64), Compression.Deflate)), let _t = ((type nullable text) meta [Serialized.Text = true]) in type table [#"Coluna 1" = _t]),
				    #"Tipo Alterado" = Table.TransformColumnTypes(Fonte,{{"Coluna 1", type text}})
				in
				    #"Tipo Alterado"

	annotation PBI_ResultType = Table

